### PR TITLE
Fix the is_expired function of Token

### LINKED ISSUE #8: Automatic token refreshing does not work
The function `is_expired` of a `Token` currently always returns false because the created timestamp will always be before the expiry timestamp. This means the auto refreshing functionality will never be triggered.

### PR DESCRIPTION
**Pull request by Multimodcrafter**
This should fix #8

### CODE REVIEW

**Comment by Bogpan** [comment]
That was a stupid oversight, thanks!

**Comment by AregevDev** [comment]
Can you publish this fix on `creates.io`? I encountered the same issue :smile:

**Comment by Bogpan** [comment]
Oops. Sure thing, I was trying to avoid releasing a new version for each small fix. Will update it on crates.io shortly. Happy to know people are actually using the library haha.

Do note I've made big progress on the rewrite and it will release relatively soon (working on documentation currently, then examples, testing, CI pipeline and it will be done). With that said, I'll fix any bugs I can find in v3 in the future.

**Comment by Multimodcrafter** [comment]
@AregevDev 
You can also patch crates.io in your current project as described here (last paragraph in the linked section): https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#testing-a-bugfix

This is the standard way of getting a version of a crate that has not been published yet ;)

**Comment by AregevDev** [comment]
Yeah I know, I wasn't feeling like fetching from git... 🫣

**Pull request merged**
